### ISSUE TITLE
bug：新用户点击文字传情crash

### ISSUE THREAD

**Issue by ZhaoLike** [lzan13/VMMatch#3]
2019-07-11 11:49:47.539 19799-19799/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vmloft.develop.app.match, PID: 19799
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.vmloft.develop.app.match.request.bean.AAccount.getAvatar()' on a null object reference
        at com.vmloft.develop.app.match.ui.main.home.MatchActivity.f(Unknown Source:98)
        at com.vmloft.develop.app.match.ui.main.home.MatchActivity.c(Unknown Source:0)
        at com.vmloft.develop.app.match.ui.main.home.MatchActivity$1.a(Unknown Source:66)
        at com.vmloft.develop.app.match.ui.main.home.MatchActivity$1.onSuccess(Unknown Source:2)
        at com.vmloft.develop.app.match.b.d$2.a(Unknown Source:4)
        at com.vmloft.develop.app.match.b.d$2.a(Unknown Source:2)
        at com.vmloft.develop.app.match.b.g.a(Unknown Source:10)
        at com.vmloft.develop.app.match.b.g.a_(Unknown Source:2)
        at b.a.e.e.b.m$a.a_(Unknown Source:8)
        at b.a.e.e.b.h$a.f(Unknown Source:47)
        at b.a.e.e.b.h$a.run(Unknown Source:8)
        at b.a.a.b.b$b.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:909)

**Comment by lzan13** [comment]
已解决，感谢反馈，是有人提交的匹配数据出错导致
